---
title: "Animation"
author: "Anna Kaplan and Arlton Gilbert"
date: "11/05/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

```{r libraries}
library(lubridate)
library(dplyr)
library(ggplot2)
library(plotly)
library(rnaturalearth)
library(gifski)
library(transformr)
library(sf)
library(gganimate)
library(WDI)
library(countrycode)
```

```{r downloads}
# download data directly
ncov <- read.csv("https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv")
# convert Date from factor to date class
ncov <- ncov %>% mutate(Date = ymd(Date))
# save
last_Date_unf = max(ncov$Date)
last_Date = format(last_Date_unf,"%d %b %Y")
save(ncov, file = paste0("ncov-",gsub("-","",last_Date_unf),".Rdata",sep=""))
#View(ncov)
ncov = ncov %>% mutate(Confirmed = ifelse(is.na(Confirmed), 0, Confirmed)) %>% mutate(Deaths = ifelse(is.na(Deaths), 0, Deaths)) %>% mutate(Recovered = ifelse(is.na(Recovered), 0, Recovered))
#View(ncov)
```


```{r Greenland}
#We think Greenland should be separate
ncov = ncov %>% mutate(Country.Region = ifelse(Province.State == "Greenland","Greenland",paste0(Country.Region))) %>% mutate(Province.State = ifelse(Province.State == "Greenland","",paste0(Province.State)))
```


```{r groupCount}
ncovgroup <- ncov %>% group_by(Country.Region,Date) %>% summarise(Confirmed = sum(Confirmed),Recovered = sum(Recovered),Deaths = sum(Deaths))
```

```{r map}
world <- ne_countries(returnclass = "sf")

# what we want to do is to merge the geometry column from the 'world' dataset
# with the rest of the data from the `gapminder` dataset

# one possible problem is that we might not have gapminder data for every country in
# the world. Another is that names might not match up exactly. Let's check on this.

ncovgroup$Country.Region[ncovgroup$Country.Region == "US"] = "United States"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Korea, South"] = "Republic of Korea"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Taiwan*"] = "Taiwan"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Congo (Brazzaville)"] = "Republic of Congo"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Congo (Kinshasa)"] = "Democratic Republic of the Congo"
ncovgroup$Country.Region[ncovgroup$Country.Region == "North Macedonia"] = "Macedonia"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Czechia"] = "Czech Republic"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Gambia, The"] = "The Gambia"
ncovgroup$Country.Region[ncovgroup$Country.Region == "Monaco"] = "France"
world$name_long[world$name_long == "Russian Federation"] = "Russia"
world$name_long[world$name_long == "Côte d'Ivoire"] = "Cote d'Ivoire"
world$name_long[world$name_long == "Brunei Darussalam"] = "Brunei"
world$name_long[world$name_long == "Swaziland"] = "Eswatini"


# gapminder countries
gapnames <- as.character(unique(ncovgroup$Country.Region))
# nearth countries
nenames <- unique(world$name_long)
# number of countries in gapminder not in nearth
sum(!(gapnames %in% nenames))
# which ones 
gapnames[!(gapnames %in% nenames)]
nenames[!(nenames %in% gapnames)]


# we could go back and see if they really aren't there, or just a difference in  
# spelling. For now, we'll just assume we don't have data for these countries and 
# move on -- there are not too many of these tricky-to-handle countries

# we only need the geometry column from `world` (remember we want to merge this
# into the gapminder data), so just select the columns we need
world <- world %>% dplyr::select(name = name_long, geometry)

# do a database join to add the sfc (simple feature column: the geometry) to 
# the gapminder data
world_gap <- inner_join(ncovgroup, world, by = c("Country.Region" = "name"))
class(world_gap)

# inner_join resets object class so not an sf object any more. Need to tell R
# again that its an sf object
world_gap <- st_as_sf(world_gap)

```

```{r addpops}
allWDI <- WDI(country = "all", indicator = "SP.POP.TOTL", extra=TRUE, start=2018, end=2018)
regionhelp = allWDI %>% rename(Region=region) %>% dplyr::select(c("iso2c","Region","SP.POP.TOTL"))

world_gap$iso2c = countrycode(sourcevar = world_gap$Country.Region,
                                             origin = "country.name",
                                             destination = "iso2c")
world_gap_iso = left_join(world_gap,regionhelp,by = "iso2c")
unique(world_gap_iso %>% filter(is.na(Region)) %>% select(Country.Region)) #The regions where we didn't have values
#We don't have population info for Kosovo, Macedonia, Taiwant and Western Sahara

world_gap_iso = world_gap_iso %>% mutate(Frac = Confirmed/SP.POP.TOTL*1000000)
#View(world_gap_iso)
```


```{r plot}
options(scipen=10000)
# plot with transition_time - one frame per year
ptt <- ggplot(world_gap_iso) +
  geom_sf(data = world, colour = "#ffffff20", fill = "#2d2d2d60", size = .5) +
  geom_sf(aes(fill = Frac, frame = Date)) +
  ggtitle("COVID-19 Relative Infection Rates") +
  labs(caption = paste0("Data Updated: ",last_Date)) +
  theme(plot.title = element_text(hjust=0.5)) +
  labs(fill = "Cases per Mill population") +
  scale_fill_continuous(high = "red3", low = "lightgoldenrod",trans = "log", breaks=c(0.01,0.1,1,10,100,1000,10000),labels=c(0.01,0.1,1,10,100,1000,10000)) +
  # Here comes the gganimate specific bits
  labs(subtitle = 'Date: {frame_time}') +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  transition_time(Date) +
  ease_aes('linear')
#ptt
```

```{r plotConf}

# plot with transition_time - one frame per year
pttconf <- ggplot(world_gap) +
  geom_sf(data = world, colour = "#ffffff20", fill = "#2d2d2d60", size = .5) +
  geom_sf(aes(fill = Confirmed, frame = Date)) +
  ggtitle(label = "Confirmed COVID-19 Cases") +
  labs(caption = paste0("Data Updated: ",last_Date)) +
  theme(plot.title = element_text(hjust=0.5)) +
  labs(fill = "Confirmed Cases") +
  scale_fill_continuous(high = "red3", low = "lightgoldenrod",trans = "log", breaks=c(1,10,100,1000,10000,100000),labels=c(1,10,100,1000,10000,100000)) +
  # Here comes the gganimate specific bits
  labs(subtitle = 'Date: {frame_time}') +
  theme(plot.subtitle = element_text(hjust=0.5)) +
  transition_time(Date) +
  ease_aes('linear')
#pttconf
```

```{r save}
anim_save(filename = "map perc.gif", animation = ptt, height = 600, width = 1000)
```

```{r saveconf}
anim_save(filename = "map conf.gif", animation = pttconf, height = 600, width = 1000)
```
